server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres_for_card_management:5432/card_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

card:
  encryption:
    key: ${CARD_ENCRYPTION_KEY:mySuperSecretKey123}

jwt:
  secret: ${JWT_SECRET:}
  expiration: 86400000

springdoc:
  swagger-ui:
    urls-primary-name: Localhost (HTTP)
    url: http://localhost:8080/v3/api-docs
